language: node_js

node_js:
  - '12'
  - '14'
  - '15'

branches:
  only:
    - master
    - travis-ci

install:
  - for dir in mingle.*; do (cd $dir && [ -e package.json ] && npm install --no-save --no-package-lock || true); done && git checkout .
  - npm install -g nyc prove

script:
  - for dir in mingle.*; do (cd $dir && [ -e package.json ] && nyc npm test || true); done && git checkout .
