sudo: false

language: node_js

node_js:
  - '4'
  - '6'
  - '8'

branches:
  only:
    - master
    - travis-ci

install:
  - for dir in mingle.*; do (cd $dir && npm install --no-package-lock --no-save); done
  - npm install --no-package-lock --no-save
  - npm install -g proof istanbul coveralls
  - git checkout .

script: t/test
