sudo: false

language: node_js

node_js:
  - '0.10'
  - '4'
  - '6'

branches:
  only:
    - master
    - travis-ci

# Not using `npm install --dev` because it is recursive. It will pull in the all
# development dependencies for CoffeeScript. Way too much spew in the Travis CI
# build output.

before_install:
  - npm install proof istanbul coveralls
  - for dir in mingle.*; do (cd $dir && npm install); done

script: t/test
