sudo: false

language: node_js

node_js:
  - '4'
  - '6'
  - '8'

branches:
  only:
    - master
    - travis-ci

install:
  - npm install proof istanbul coveralls@2
  - for dir in mingle.*; do (cd $dir && npm install); done

script: t/test
